name = "clubpass-backend"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "clubpass-jwt-secret-2024-production"
CLOUDINARY_CLOUD_NAME = "tczzvpz3"
CLOUDINARY_API_KEY = "299913721364446"
CLOUDINARY_API_SECRET = "yRZHF31eOdKJL2HsEUFX-YSWn3g"
VAPID_PUBLIC_KEY = "BK6B6WosZj6XwzzyWEpEDXnFvzrRW1oLQJcgV-UeT9Tm6Fcg3c5BmHXsJ0ZzZ5FgQGkkGDqT90E1E2xKsLR3Yec"
VAPID_PRIVATE_KEY = "qfGLO_irX5wJSFCZDf5LC4GTQ_eV176zFhHQb7gn3DY"
VAPID_SUBJECT = "mailto:admin@infin8access.local"

[[d1_databases]]
binding = "DB"
database_name = "clubpass-db"
database_id = "f018958f-2751-40ff-a5f0-52a11d57994e"